# Generated by Django 2.2 on 2019-04-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='content',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='content3',
        ),
        migrations.AddField(
            model_name='shoe',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='brand',
            field=models.CharField(default='Nike', max_length=20),
        ),
        migrations.AddField(
            model_name='shoe',
            name='color',
            field=models.CharField(default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='shoe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shoe/'),
        ),
        migrations.AddField(
            model_name='shoe',
            name='name',
            field=models.CharField(default='Boosts', max_length=30),
        ),
        migrations.AddField(
            model_name='shoe',
            name='price',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='shoe',
            name='size',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='shoe',
            name='stock',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='shoe',
            name='style',
            field=models.CharField(default='sneakers', max_length=20),
        ),
    ]
