# Generated by Django 2.2 on 2019-05-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0004_shoe_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
