# Generated by Django 2.2 on 2019-05-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0005_shoe_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='like',
            field=models.BooleanField(default=True),
        ),
    ]
