# Generated by Django 2.2 on 2019-04-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shoe', '0003_shoe_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('availability', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(blank=True, null=True, to='shoe.Shoe')),
            ],
        ),
    ]
